CREATE USER ADMIN_HUIT IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, DBA TO ADMIN_HUIT;
GRANT UNLIMITED TABLESPACE TO ADMIN_HUIT;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO ADMIN_HUIT;

GRANT SELECT ON SYS.SEQ$ TO ADMIN_HUIT;
GRANT SELECT ON SYS.USER$ TO ADMIN_HUIT;

-- Tạo Tablespace 
CREATE TABLESPACE TBS_DIEMDANH_DATA 
    DATAFILE 'diemdanh_data.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M;
    
-- Tạo Profile quản lí
CREATE PROFILE PRO_SECURE_USER LIMIT
    SESSIONS_PER_USER 3      
    FAILED_LOGIN_ATTEMPTS 5   
    PASSWORD_LIFE_TIME 90     
    IDLE_TIME 30;        
    
GRANT CONNECT, RESOURCE, DBA TO ADMIN_HUIT;
GRANT UNLIMITED TABLESPACE TO ADMIN_HUIT;

-- Các quyền đặc biệt để làm bảo mật nâng cao
GRANT EXECUTE ON DBMS_RLS TO ADMIN_HUIT;    
GRANT EXECUTE ON DBMS_FGA TO ADMIN_HUIT;   
GRANT EXECUTE ON DBMS_CRYPTO TO ADMIN_HUIT; 
GRANT AUDIT SYSTEM TO ADMIN_HUIT;           

-- Gán Tablespace và Profile cho user
ALTER USER ADMIN_HUIT DEFAULT TABLESPACE TBS_DIEMDANH_DATA;
ALTER USER ADMIN_HUIT PROFILE PRO_SECURE_USER;
ALTER USER ADMIN_HUIT QUOTA UNLIMITED ON TBS_DIEMDANH_DATA;

CREATE TABLE VAI_TRO (
    MA_VAI_TRO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    TEN_VAI_TRO VARCHAR2(50),
    MO_TA NVARCHAR2(200)
);

CREATE TABLE NGUOI_DUNG (
    MA_NGUOI_DUNG NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TEN_DANG_NHAP VARCHAR2(50) NOT NULL UNIQUE,
    MAT_KHAU_HASH VARCHAR2(255) NOT NULL, 
    HO_TEN NVARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100),
    SDT VARCHAR2(20),
    MA_VAI_TRO NUMBER REFERENCES VAI_TRO(MA_VAI_TRO),
    ANH_DAI_DIEN VARCHAR2(255),
    SALT VARCHAR2(100),                 
    PUBLIC_KEY CLOB,                    
    PRIVATE_KEY_ENC CLOB,               
    TRANG_THAI_KHOA NUMBER(1) DEFAULT 0, 
    OLS_LABEL NUMBER DEFAULT 1          
);

CREATE TABLE HOC_KY (
    MA_HOC_KY NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TEN_HOC_KY NVARCHAR2(50) NOT NULL, 
    NGAY_BAT_DAU DATE,
    NGAY_KET_THUC DATE
);

CREATE TABLE MON_HOC (
    MA_MON VARCHAR2(20) PRIMARY KEY, 
    TEN_MON NVARCHAR2(100) NOT NULL,
    SO_TIN_CHI NUMBER
);

CREATE TABLE LOP_HOC_PHAN (
    MA_LOP_HP NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MA_LOP_CODE VARCHAR2(50) NOT NULL, 
    MA_MON VARCHAR2(20) REFERENCES MON_HOC(MA_MON),
    MA_GIANG_VIEN NUMBER REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG),
    MA_HOC_KY NUMBER REFERENCES HOC_KY(MA_HOC_KY),
    SI_SO_TOI_DA NUMBER DEFAULT 60
);

CREATE TABLE DANG_KY_LOP (
    MA_DANG_KY NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MA_LOP_HP NUMBER REFERENCES LOP_HOC_PHAN(MA_LOP_HP),
    MA_SINH_VIEN NUMBER REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG),
    NGAY_VAO_LOP DATE DEFAULT SYSDATE
);

CREATE TABLE LICH_HOC (
    MA_BUOI_HOC NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MA_LOP_HP NUMBER REFERENCES LOP_HOC_PHAN(MA_LOP_HP),
    NGAY_HOC DATE NOT NULL,
    GIO_BAT_DAU VARCHAR2(10),    
    GIO_KET_THUC VARCHAR2(10),   
    PHONG_HOC VARCHAR2(50),
    CHUOI_QR VARCHAR2(255),       
    MA_OTP VARCHAR2(6),           
    TRANG_THAI NUMBER(1) DEFAULT 1 
);

CREATE TABLE LICHSU_DIEMDANH (
    MA_LOG NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MA_BUOI_HOC NUMBER REFERENCES LICH_HOC(MA_BUOI_HOC),
    MA_SINH_VIEN NUMBER REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG),
    THOI_GIAN_DIEM_DANH TIMESTAMP DEFAULT SYSTIMESTAMP,
    TRANG_THAI NVARCHAR2(20),      
    PHUONG_THUC VARCHAR2(20),      
    THIET_BI_ENC RAW(2000),      
    VI_TRI_ENC RAW(2000),        
    CHU_KY_SO RAW(2000)              
);

--Mỗi sinh viên chỉ điểm danh 1 lần trong buổi học 
ALTER TABLE LICHSU_DIEMDANH
ADD CONSTRAINT UNQ_SV_BUOIHOC UNIQUE (MA_BUOI_HOC, MA_SINH_VIEN);

-- Tạo bảng lưu danh sách chờ duyệt
CREATE TABLE DANG_KY_CHO (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HO_TEN NVARCHAR2(100),
    EMAIL VARCHAR2(100),
    THOI_GIAN DATE DEFAULT SYSDATE
);

--người dùng đổi mật khẩu sau khi đăng kí 
ALTER TABLE NGUOI_DUNG ADD CAN_DOI_MAT_KHAU NUMBER(1) DEFAULT 1;
UPDATE NGUOI_DUNG SET FORCE_CHANGE_PASS = 0;
COMMIT;

--Thêm người dùng 
CREATE OR REPLACE PROCEDURE PROC_THEM_NGUOI_DUNG_AUTO (
    p_name IN NVARCHAR2, 
    p_email IN VARCHAR2, 
    p_role IN NUMBER
) IS
    v_salt VARCHAR2(100); 
    v_hash VARCHAR2(255);
    v_prefix VARCHAR2(5);
    v_next_id NUMBER;
    v_new_username VARCHAR2(50);
BEGIN
    -- Xác định tiền tố là sinh viên hay giảng viên 
    IF p_role = 2 THEN v_prefix := 'GV'; ELSE v_prefix := 'SV'; END IF;
    -- Tìm số thứ tự tiếp theo
    BEGIN
        SELECT NVL(MAX(TO_NUMBER(SUBSTR(TEN_DANG_NHAP, 3))), 0) + 1 
        INTO v_next_id FROM NGUOI_DUNG WHERE TEN_DANG_NHAP LIKE v_prefix || '%';
    EXCEPTION WHEN OTHERS THEN v_next_id := 1; END;
    -- Tạo Username
    v_new_username := v_prefix || LPAD(v_next_id, 3, '0');

    -- Tạo mật khẩu cố định '123'
    v_salt := FUNC_GEN_SALT();    
    v_hash := FUNC_HASH_PASS('123', v_salt);
    INSERT INTO NGUOI_DUNG (
        TEN_DANG_NHAP, MAT_KHAU_HASH, SALT, HO_TEN, EMAIL, MA_VAI_TRO, FORCE_CHANGE_PASS
    ) VALUES (
        v_new_username, v_hash, v_salt, p_name, p_email, p_role, 1
    );
    COMMIT;
END;
/

--Xóa người dùng 
CREATE OR REPLACE PROCEDURE PROC_XOA_NGUOI_DUNG (p_user_id IN NUMBER) IS
BEGIN
    DELETE FROM LICHSU_DIEMDANH WHERE MA_SINH_VIEN = p_user_id;
    DELETE FROM DANG_KY_LOP WHERE MA_SINH_VIEN = p_user_id;
    DELETE FROM AUDIT_LOG WHERE MA_NGUOI_DUNG = p_user_id;
    DELETE FROM NGUOI_DUNG WHERE MA_NGUOI_DUNG = p_user_id;
    COMMIT;
END;
/

--Bảng Audit log 
CREATE TABLE AUDIT_LOG (
    MA_LOG NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MA_NGUOI_DUNG NUMBER REFERENCES NGUOI_DUNG(MA_NGUOI_DUNG),
    HANH_DONG NVARCHAR2(100) NOT NULL,    
    CHI_TIET NVARCHAR2(500),              
    IP_ADDRESS VARCHAR2(50),
    USER_AGENT VARCHAR2(255),
    THOI_GIAN TIMESTAMP DEFAULT SYSTIMESTAMP,
    TRANG_THAI NVARCHAR2(20)
);

-- Tạo index tối ưu cho truy vấn log 
CREATE INDEX idx_audit_user ON AUDIT_LOG(MA_NGUOI_DUNG);
CREATE INDEX idx_audit_time ON AUDIT_LOG(THOI_GIAN);

-- Bảng Log Audit cho Trigger 
CREATE TABLE LOG_DB_CHANGES (
    ID_LOG NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_DB VARCHAR2(50),
    ACTION_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    ACTION_TYPE VARCHAR2(20),
    TABLE_NAME VARCHAR2(50),
    OLD_DATA NVARCHAR2(2000),
    NEW_DATA NVARCHAR2(2000)
);

--Trigger kiểm soát thời gian điểm danh
CREATE OR REPLACE TRIGGER TRG_CHECK_THOI_GIAN_DIEMDANH
BEFORE INSERT ON LICHSU_DIEMDANH
FOR EACH ROW
DECLARE
    v_ngay DATE; v_gio_bd VARCHAR2(10); v_gio_kt VARCHAR2(10);
    v_now VARCHAR2(5);
BEGIN
    SELECT NGAY_HOC, GIO_BAT_DAU, GIO_KET_THUC 
    INTO v_ngay, v_gio_bd, v_gio_kt
    FROM LICH_HOC WHERE MA_BUOI_HOC = :NEW.MA_BUOI_HOC;
    
    v_now := TO_CHAR(SYSDATE, 'HH24:MI');
    
    IF TRUNC(SYSDATE) <> v_ngay THEN
        RAISE_APPLICATION_ERROR(-20001, 'Không phải ngày học!');
    END IF;
    
    IF v_now < v_gio_bd OR v_now > v_gio_kt THEN
        RAISE_APPLICATION_ERROR(-20002, 'Chưa đến giờ hoặc đã hết giờ!');
    END IF;
END;
/

-- Trigger giám sát người dùng (thêm, xóa, sửa)
CREATE OR REPLACE TRIGGER TRG_AUDIT_USER_CHANGES
AFTER INSERT OR UPDATE OR DELETE ON NGUOI_DUNG
FOR EACH ROW
DECLARE 
    v_user VARCHAR2(50);
BEGIN
    SELECT USER INTO v_user FROM DUAL; 
    
    IF INSERTING THEN
        INSERT INTO LOG_DB_CHANGES (USER_DB, ACTION_TYPE, TABLE_NAME, NEW_DATA)
        VALUES (v_user, 'INSERT', 'NGUOI_DUNG', 'New User: ' || :NEW.TEN_DANG_NHAP || ' (' || :NEW.HO_TEN || ')');
        
    ELSIF UPDATING THEN
        INSERT INTO LOG_DB_CHANGES (USER_DB, ACTION_TYPE, TABLE_NAME, OLD_DATA, NEW_DATA)
        VALUES (v_user, 'UPDATE', 'NGUOI_DUNG', 
                'User: ' || :OLD.TEN_DANG_NHAP, 
                'Updated Info (Role/Email/Pass)');
                
    ELSIF DELETING THEN
        INSERT INTO LOG_DB_CHANGES (USER_DB, ACTION_TYPE, TABLE_NAME, OLD_DATA)
        VALUES (v_user, 'DELETE', 'NGUOI_DUNG', 'Deleted User: ' || :OLD.TEN_DANG_NHAP || ' - ID: ' || :OLD.MA_NGUOI_DUNG);
    END IF;
END;
/

-- Trigger giám sát lịch học 
CREATE OR REPLACE TRIGGER TRG_AUDIT_LICH_HOC
AFTER UPDATE ON LICH_HOC
FOR EACH ROW
DECLARE 
    v_user VARCHAR2(50);
BEGIN
    SELECT USER INTO v_user FROM DUAL;
    IF :NEW.MA_OTP IS NOT NULL AND (:OLD.MA_OTP IS NULL OR :NEW.MA_OTP != :OLD.MA_OTP) THEN
        INSERT INTO LOG_DB_CHANGES (USER_DB, ACTION_TYPE, TABLE_NAME, NEW_DATA)
        VALUES (v_user, 'UPDATE', 'LICH_HOC', 'Generated OTP: ' || :NEW.MA_OTP || ' for Schedule ID: ' || :NEW.MA_BUOI_HOC);
    END IF;
END;
/
COMMIT;

BEGIN
    PROC_THEM_NGUOI_DUNG('admin', '123', 'Quản Trị Viên', 'admin@huit.edu.vn', 1);
END;
/

BEGIN
    INSERT INTO VAI_TRO (MA_VAI_TRO, TEN_VAI_TRO) SELECT 1, 'Admin' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM VAI_TRO WHERE MA_VAI_TRO = 1);
    INSERT INTO VAI_TRO (MA_VAI_TRO, TEN_VAI_TRO) SELECT 2, 'Giảng viên' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM VAI_TRO WHERE MA_VAI_TRO = 2);
    INSERT INTO VAI_TRO (MA_VAI_TRO, TEN_VAI_TRO) SELECT 3, 'Sinh viên' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM VAI_TRO WHERE MA_VAI_TRO = 3);
    COMMIT;
END;
/
SET SERVEROUTPUT ON;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

BEGIN
    INSERT INTO HOC_KY (TEN_HOC_KY, NGAY_BAT_DAU, NGAY_KET_THUC) 
    VALUES (N'Học kỳ 1 2025-2026', TRUNC(SYSDATE, 'YEAR'), TRUNC(SYSDATE, 'YEAR') + 365);

    INSERT INTO MON_HOC VALUES ('SEC101', N'An toàn thông tin', 3);
    INSERT INTO MON_HOC VALUES ('PRG202', N'Lập trình Python', 4);
    INSERT INTO MON_HOC VALUES ('WEB301', N'Lập trình Web nâng cao', 3);
    INSERT INTO MON_HOC VALUES ('DBI202', N'Hệ quản trị CSDL Oracle', 4);
    INSERT INTO MON_HOC VALUES ('AI101',  N'Trí tuệ nhân tạo', 3);
    INSERT INTO MON_HOC VALUES ('IOT102', N'Lập trình IoT', 3);
    INSERT INTO MON_HOC VALUES ('JAV101', N'Lập trình Java', 4);
    INSERT INTO MON_HOC VALUES ('NET101', N'Mạng máy tính', 3);
    
    COMMIT;
END;
/

BEGIN
    BEGIN PROC_THEM_NGUOI_DUNG('admin', '123', N'Quản Trị Viên', 'admin@huit.edu.vn', 1); EXCEPTION WHEN OTHERS THEN NULL; END;
    PROC_THEM_NGUOI_DUNG('GV001', '123', N'TS. Nguyễn Văn Hùng', 'gv001@huit.edu.vn', 2);
    PROC_THEM_NGUOI_DUNG('GV002', '123', N'ThS. Lê Thị Mai', 'gv002@huit.edu.vn', 2);
    PROC_THEM_NGUOI_DUNG('GV003', '123', N'TS. Trần Thanh Sang', 'gv003@huit.edu.vn', 2);
    PROC_THEM_NGUOI_DUNG('GV004', '123', N'ThS. Phạm Thu Hương', 'gv004@huit.edu.vn', 2);
    PROC_THEM_NGUOI_DUNG('GV005', '123', N'TS. Đặng Quang Vinh', 'gv005@huit.edu.vn', 2);
    PROC_THEM_NGUOI_DUNG('GV006', '123', N'ThS. Vũ Văn Tuấn', 'gv006@huit.edu.vn', 2);
    PROC_THEM_NGUOI_DUNG('GV007', '123', N'TS. Hoàng Thị Lan', 'gv007@huit.edu.vn', 2);

    PROC_THEM_NGUOI_DUNG('SV001', '123', N'Trần Phi Long', 'sv001@st.huit.edu.vn', 3);
    PROC_THEM_NGUOI_DUNG('SV002', '123', N'Nguyễn Thị Hoa', 'sv002@st.huit.edu.vn', 3);
    PROC_THEM_NGUOI_DUNG('SV003', '123', N'Lê Văn Cường', 'sv003@st.huit.edu.vn', 3);
    PROC_THEM_NGUOI_DUNG('SV004', '123', N'Phạm Minh Đức', 'sv004@st.huit.edu.vn', 3);
    PROC_THEM_NGUOI_DUNG('SV005', '123', N'Hoàng Thùy Linh', 'sv005@st.huit.edu.vn', 3);
    -- Các SV còn lại tạo tự động
    FOR i IN 6..30 LOOP
        PROC_THEM_NGUOI_DUNG('SV0' || CASE WHEN i<10 THEN '0'||i ELSE TO_CHAR(i) END, 
                             '123', 
                             N'Sinh Viên Số '||i, 
                             'sv0'||i||'@st.huit.edu.vn', 3);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('--- Đã tạo xong User---');
END;
/

--Lớp học phần
DECLARE
    v_hk NUMBER;
    v_gv1 NUMBER; v_gv2 NUMBER; v_gv3 NUMBER; v_gv4 NUMBER; 
    v_gv5 NUMBER; v_gv6 NUMBER; v_gv7 NUMBER;
BEGIN
    SELECT MA_HOC_KY INTO v_hk FROM HOC_KY WHERE ROWNUM=1;    
    SELECT MA_NGUOI_DUNG INTO v_gv1 FROM NGUOI_DUNG WHERE TEN_DANG_NHAP='GV001';
    SELECT MA_NGUOI_DUNG INTO v_gv2 FROM NGUOI_DUNG WHERE TEN_DANG_NHAP='GV002';
    SELECT MA_NGUOI_DUNG INTO v_gv3 FROM NGUOI_DUNG WHERE TEN_DANG_NHAP='GV003';
    SELECT MA_NGUOI_DUNG INTO v_gv4 FROM NGUOI_DUNG WHERE TEN_DANG_NHAP='GV004';
    SELECT MA_NGUOI_DUNG INTO v_gv5 FROM NGUOI_DUNG WHERE TEN_DANG_NHAP='GV005';
    SELECT MA_NGUOI_DUNG INTO v_gv6 FROM NGUOI_DUNG WHERE TEN_DANG_NHAP='GV006';
    SELECT MA_NGUOI_DUNG INTO v_gv7 FROM NGUOI_DUNG WHERE TEN_DANG_NHAP='GV007';
    INSERT INTO LOP_HOC_PHAN (MA_LOP_CODE, MA_MON, MA_GIANG_VIEN, MA_HOC_KY) VALUES ('L01_SEC', 'SEC101', v_gv1, v_hk);
    INSERT INTO LOP_HOC_PHAN (MA_LOP_CODE, MA_MON, MA_GIANG_VIEN, MA_HOC_KY) VALUES ('L02_DBI', 'DBI202', v_gv1, v_hk);
    INSERT INTO LOP_HOC_PHAN (MA_LOP_CODE, MA_MON, MA_GIANG_VIEN, MA_HOC_KY) VALUES ('L03_PY',  'PRG202', v_gv2, v_hk);
    INSERT INTO LOP_HOC_PHAN (MA_LOP_CODE, MA_MON, MA_GIANG_VIEN, MA_HOC_KY) VALUES ('L04_WEB', 'WEB301', v_gv3, v_hk);
    INSERT INTO LOP_HOC_PHAN (MA_LOP_CODE, MA_MON, MA_GIANG_VIEN, MA_HOC_KY) VALUES ('L05_AI',  'AI101',  v_gv4, v_hk);
    INSERT INTO LOP_HOC_PHAN (MA_LOP_CODE, MA_MON, MA_GIANG_VIEN, MA_HOC_KY) VALUES ('L06_IOT', 'IOT102', v_gv5, v_hk);
    INSERT INTO LOP_HOC_PHAN (MA_LOP_CODE, MA_MON, MA_GIANG_VIEN, MA_HOC_KY) VALUES ('L07_JAV', 'JAV101', v_gv6, v_hk);
    INSERT INTO LOP_HOC_PHAN (MA_LOP_CODE, MA_MON, MA_GIANG_VIEN, MA_HOC_KY) VALUES ('L08_NET', 'NET101', v_gv7, v_hk);
    COMMIT;
END;
/

-- Xếp lớp 
DECLARE
    v_sv_id NUMBER;
BEGIN
    FOR r_lhp IN (SELECT MA_LOP_HP FROM LOP_HOC_PHAN) LOOP
        SELECT MA_NGUOI_DUNG INTO v_sv_id FROM NGUOI_DUNG WHERE TEN_DANG_NHAP = 'SV001';
        INSERT INTO DANG_KY_LOP (MA_LOP_HP, MA_SINH_VIEN) VALUES (r_lhp.MA_LOP_HP, v_sv_id);
        SELECT MA_NGUOI_DUNG INTO v_sv_id FROM NGUOI_DUNG WHERE TEN_DANG_NHAP = 'SV002';
        INSERT INTO DANG_KY_LOP (MA_LOP_HP, MA_SINH_VIEN) VALUES (r_lhp.MA_LOP_HP, v_sv_id);        
        FOR k IN 3..15 LOOP
             SELECT MA_NGUOI_DUNG INTO v_sv_id FROM NGUOI_DUNG 
             WHERE TEN_DANG_NHAP = 'SV0'||CASE WHEN k<10 THEN '0'||k ELSE TO_CHAR(k) END;
             IF MOD(k + r_lhp.MA_LOP_HP, 2) = 0 THEN 
                INSERT INTO DANG_KY_LOP (MA_LOP_HP, MA_SINH_VIEN) VALUES (r_lhp.MA_LOP_HP, v_sv_id);
             END IF;
        END LOOP;
    END LOOP;
    COMMIT;
END;
/

DECLARE
    v_monday DATE := TRUNC(SYSDATE, 'IW'); 
BEGIN
    INSERT INTO LICH_HOC (MA_LOP_HP, NGAY_HOC, GIO_BAT_DAU, GIO_KET_THUC, PHONG_HOC, MA_OTP)
    SELECT MA_LOP_HP, v_monday, '07:00', '11:00', 'A.301', NULL FROM LOP_HOC_PHAN WHERE MA_LOP_CODE = 'L01_SEC
    INSERT INTO LICH_HOC (MA_LOP_HP, NGAY_HOC, GIO_BAT_DAU, GIO_KET_THUC, PHONG_HOC, MA_OTP)
    SELECT MA_LOP_HP, v_monday, '13:00', '16:00', 'LAB.02', NULL FROM LOP_HOC_PHAN WHERE MA_LOP_CODE = 'L07_JAV';
    INSERT INTO LICH_HOC (MA_LOP_HP, NGAY_HOC, GIO_BAT_DAU, GIO_KET_THUC, PHONG_HOC, MA_OTP)
    SELECT MA_LOP_HP, v_monday + 1, '07:00', '11:00', 'C.202', NULL FROM LOP_HOC_PHAN WHERE MA_LOP_CODE = 'L04_WEB';
    INSERT INTO LICH_HOC (MA_LOP_HP, NGAY_HOC, GIO_BAT_DAU, GIO_KET_THUC, PHONG_HOC, MA_OTP)
    SELECT MA_LOP_HP, v_monday + 1, '13:00', '16:00', 'LAB.01', NULL FROM LOP_HOC_PHAN WHERE MA_LOP_CODE = 'L02_DBI';
    INSERT INTO LICH_HOC (MA_LOP_HP, NGAY_HOC, GIO_BAT_DAU, GIO_KET_THUC, PHONG_HOC, MA_OTP)
    SELECT MA_LOP_HP, v_monday + 2, '17:30', '20:30', 'A.505', NULL FROM LOP_HOC_PHAN WHERE MA_LOP_CODE = 'L03_PY';
    INSERT INTO LICH_HOC (MA_LOP_HP, NGAY_HOC, GIO_BAT_DAU, GIO_KET_THUC, PHONG_HOC, MA_OTP)
    SELECT MA_LOP_HP, v_monday + 3, '07:00', '11:00', 'B.101', NULL FROM LOP_HOC_PHAN WHERE MA_LOP_CODE = 'L08_NET';
    INSERT INTO LICH_HOC (MA_LOP_HP, NGAY_HOC, GIO_BAT_DAU, GIO_KET_THUC, PHONG_HOC, MA_OTP)
    SELECT MA_LOP_HP, v_monday + 4, '13:00', '16:00', 'A.404', NULL FROM LOP_HOC_PHAN WHERE MA_LOP_CODE = 'L05_AI';
    INSERT INTO LICH_HOC (MA_LOP_HP, NGAY_HOC, GIO_BAT_DAU, GIO_KET_THUC, PHONG_HOC, MA_OTP)
    SELECT MA_LOP_HP, v_monday + 5, '07:00', '11:00', 'LAB.IOT', NULL FROM LOP_HOC_PHAN WHERE MA_LOP_CODE = 'L06_IOT';
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Đã tạo Lịch học tuần này thành công');
END;
/


SET SERVEROUTPUT ON;
DECLARE
    v_gv_id NUMBER;
    v_lop_hp_id NUMBER;
    v_sv_id NUMBER;
BEGIN
    SELECT MA_NGUOI_DUNG INTO v_gv_id FROM NGUOI_DUNG WHERE TEN_DANG_NHAP = 'GV001';

    BEGIN
        SELECT MA_LOP_HP INTO v_lop_hp_id
        FROM LOP_HOC_PHAN
        WHERE MA_GIANG_VIEN = v_gv_id AND MA_MON = 'SEC101'
        FETCH FIRST 1 ROWS ONLY;
    EXCEPTION WHEN NO_DATA_FOUND THEN
        SELECT MA_LOP_HP INTO v_lop_hp_id
        FROM LOP_HOC_PHAN WHERE MA_GIANG_VIEN = v_gv_id FETCH FIRST 1 ROWS ONLY;
    END;

    DELETE FROM LICHSU_DIEMDANH WHERE MA_BUOI_HOC IN (
        SELECT MA_BUOI_HOC FROM LICH_HOC WHERE PHONG_HOC IN ('A.502', 'LAB.03', 'TEST_NOW', 'DEMO_ROOM')
    );
    DELETE FROM LICH_HOC WHERE PHONG_HOC IN ('A.502', 'LAB.03', 'TEST_NOW', 'DEMO_ROOM');

    INSERT INTO LICH_HOC (MA_LOP_HP, NGAY_HOC, GIO_BAT_DAU, GIO_KET_THUC, PHONG_HOC, MA_OTP, TRANG_THAI)
    VALUES (v_lop_hp_id, TRUNC(SYSDATE), '18:00', '21:00', 'A.502', NULL, 1);

    INSERT INTO LICH_HOC (MA_LOP_HP, NGAY_HOC, GIO_BAT_DAU, GIO_KET_THUC, PHONG_HOC, MA_OTP, TRANG_THAI)
    VALUES (v_lop_hp_id, TRUNC(SYSDATE) + 1, '13:00', '16:00', 'LAB.03', NULL, 1);

    FOR r IN (SELECT 'SV001' u FROM DUAL UNION ALL SELECT 'SV002' FROM DUAL UNION ALL SELECT 'SV003' FROM DUAL) LOOP
        BEGIN
            SELECT MA_NGUOI_DUNG INTO v_sv_id FROM NGUOI_DUNG WHERE TEN_DANG_NHAP = r.u;
            
            INSERT INTO DANG_KY_LOP (MA_LOP_HP, MA_SINH_VIEN) 
            SELECT v_lop_hp_id, v_sv_id FROM DUAL
            WHERE NOT EXISTS (SELECT 1 FROM DANG_KY_LOP WHERE MA_LOP_HP = v_lop_hp_id AND MA_SINH_VIEN = v_sv_id);
        EXCEPTION WHEN OTHERS THEN NULL; END;
    END LOOP;

    COMMIT;
END;
/
SET SERVEROUTPUT ON;
DECLARE
    v_gv_id NUMBER;
    v_lop_hp_id NUMBER;
    v_sv_id NUMBER;
BEGIN
    SELECT MA_NGUOI_DUNG INTO v_gv_id FROM NGUOI_DUNG WHERE TEN_DANG_NHAP = 'GV001
    BEGIN
        SELECT MA_LOP_HP INTO v_lop_hp_id
        FROM LOP_HOC_PHAN
        WHERE MA_GIANG_VIEN = v_gv_id AND MA_MON = 'SEC101'
        FETCH FIRST 1 ROWS ONLY;
    EXCEPTION WHEN NO_DATA_FOUND THEN
        SELECT MA_LOP_HP INTO v_lop_hp_id
        FROM LOP_HOC_PHAN WHERE MA_GIANG_VIEN = v_gv_id FETCH FIRST 1 ROWS ONLY;
    END;

    DELETE FROM LICHSU_DIEMDANH WHERE MA_BUOI_HOC IN (
        SELECT MA_BUOI_HOC FROM LICH_HOC WHERE PHONG_HOC = 'TEST_DEMO' AND TRUNC(NGAY_HOC) = TRUNC(SYSDATE)
    );
    DELETE FROM LICH_HOC WHERE PHONG_HOC = 'TEST_DEMO' AND TRUNC(NGAY_HOC) = TRUNC(SYSDATE);

    INSERT INTO LICH_HOC (MA_LOP_HP, NGAY_HOC, GIO_BAT_DAU, GIO_KET_THUC, PHONG_HOC, MA_OTP, TRANG_THAI)
    VALUES (v_lop_hp_id, TRUNC(SYSDATE), '18:00', '23:59', 'TEST_DEMO', NULL, 1);

    DBMS_OUTPUT.PUT_LINE('Đã tạo lịch học Tối nay');

    FOR r IN (SELECT 'SV001' u FROM DUAL UNION ALL SELECT 'SV002' FROM DUAL UNION ALL SELECT 'SV003' FROM DUAL) LOOP
        BEGIN
            SELECT MA_NGUOI_DUNG INTO v_sv_id FROM NGUOI_DUNG WHERE TEN_DANG_NHAP = r.u;
            INSERT INTO DANG_KY_LOP (MA_LOP_HP, MA_SINH_VIEN) 
            SELECT v_lop_hp_id, v_sv_id FROM DUAL
            WHERE NOT EXISTS (SELECT 1 FROM DANG_KY_LOP WHERE MA_LOP_HP = v_lop_hp_id AND MA_SINH_VIEN = v_sv_id);
            DBMS_OUTPUT.PUT_LINE('>> Đã thêm ' || r.u || ' vào lớp để test.');
        EXCEPTION WHEN OTHERS THEN NULL; END;
    END LOOP;

    COMMIT;
END;
/


select * from NGUOI_DUNG;

--kiểm tra user vừa thêm
SELECT MA_NGUOI_DUNG, TEN_DANG_NHAP, HO_TEN, MAT_KHAU_HASH, SALT, MA_VAI_TRO
FROM NGUOI_DUNG
ORDER BY MA_NGUOI_DUNG DESC
FETCH FIRST 1 ROWS ONLY;

--Kiểm tra Log Audit 
SELECT * FROM LOG_DB_CHANGES 
WHERE TABLE_NAME = 'NGUOI_DUNG' 
ORDER BY ACTION_TIME DESC
FETCH FIRST 1 ROWS ONLY;

--AES và Hash 
--Hàm Hash Password
CREATE OR REPLACE FUNCTION FUNC_GEN_SALT RETURN VARCHAR2 IS
BEGIN RETURN RAWTOHEX(DBMS_CRYPTO.RANDOMBYTES(16)); END;
/
CREATE OR REPLACE FUNCTION FUNC_HASH_PASS(p_password IN VARCHAR2, p_salt IN VARCHAR2)
RETURN VARCHAR2 IS
    v_input RAW(2000) := UTL_I18N.STRING_TO_RAW(p_password || p_salt, 'AL32UTF8');
BEGIN
    RETURN RAWTOHEX(DBMS_CRYPTO.HASH(v_input, DBMS_CRYPTO.HASH_SH256));
END;
/
-- AES Mã hóa dữ liệu 
CREATE OR REPLACE PACKAGE PKG_BAOMAT_AES IS
    G_KEY RAW(32) := UTL_RAW.CAST_TO_RAW('KhoaBiMatChoDoAn32KyTuChoDoAn!'); 
    FUNCTION ENCRYPT_DATA(p_data IN VARCHAR2) RETURN RAW;
    FUNCTION DECRYPT_DATA(p_raw IN RAW) RETURN VARCHAR2;
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_BAOMAT_AES IS
    FUNCTION ENCRYPT_DATA(p_data IN VARCHAR2) RETURN RAW IS
    BEGIN
        IF p_data IS NULL THEN RETURN NULL; END IF;
        RETURN DBMS_CRYPTO.ENCRYPT(
            src => UTL_I18N.STRING_TO_RAW(p_data, 'AL32UTF8'),
            typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
            key => G_KEY
        );
    END;
    FUNCTION DECRYPT_DATA(p_raw IN RAW) RETURN VARCHAR2 IS
    BEGIN
        IF p_raw IS NULL THEN RETURN NULL; END IF;
        RETURN UTL_I18N.RAW_TO_CHAR(DBMS_CRYPTO.DECRYPT(
            src => p_raw,
            typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
            key => G_KEY
        ), 'AL32UTF8');
    END;
END;
/

-- MÃ HÓA LAI (HYBRID)
-- 1. PACKAGE MÃ HÓA LAI (HYBRID ENCRYPTION)
CREATE OR REPLACE PACKAGE PKG_MAHOA_LAI IS
    PROCEDURE GEN_RSA_KEYPAIR(
        p_ma_nguoi_dung IN NUMBER,
        p_out_public_key OUT CLOB,
        p_out_private_key OUT CLOB
    );
    FUNCTION ENCRYPT_WITH_PUBLIC_KEY(p_public_key IN CLOB, p_data IN VARCHAR2) RETURN RAW;
    FUNCTION DECRYPT_WITH_PRIVATE_KEY(p_private_key_enc IN CLOB, p_encrypted_data IN RAW) RETURN VARCHAR2;
    FUNCTION HYBRID_ENCRYPT(p_public_key IN CLOB, p_data IN VARCHAR2, p_out_encrypted_aes_key OUT RAW) RETURN RAW;
    FUNCTION HYBRID_DECRYPT(p_private_key_enc IN CLOB, p_encrypted_data IN RAW, p_encrypted_aes_key IN RAW) RETURN VARCHAR2;
END PKG_MAHOA_LAI;
/

-- 2. PACKAGE BODY - TRIỂN KHAI MÃ HÓA LAI
CREATE OR REPLACE PACKAGE BODY PKG_MAHOA_LAI IS
    
    G_MASTER_KEY RAW(32) := UTL_RAW.CAST_TO_RAW('4B686F6142694D6174436F446F416E21');
    
    FUNCTION DERIVE_AES128_KEY(p_input IN RAW) RETURN RAW IS
        v_hash RAW(32);
        v_key RAW(16);
    BEGIN
        v_hash := DBMS_CRYPTO.HASH(p_input, DBMS_CRYPTO.HASH_SH256);
        v_key := UTL_RAW.SUBSTR(v_hash, 1, 16);
        RETURN v_key;
    END DERIVE_AES128_KEY;
    
    -- Tạo cặp khóa RSA 
    PROCEDURE GEN_RSA_KEYPAIR(
        p_ma_nguoi_dung IN NUMBER,
        p_out_public_key OUT CLOB,
        p_out_private_key OUT CLOB
    ) IS
        v_modulus RAW(128);             
        v_exponent RAW(4) := HEXTORAW('00010001');  
        v_private_exp RAW(128);          
        v_public_key_raw RAW(200);       
        v_private_key_raw RAW(300);      
        v_private_key_encrypted RAW(2000);
        v_public_key_hex VARCHAR2(500);  -- SỬ DỤNG VARCHAR2 TRƯỚC
        v_private_key_hex VARCHAR2(4000);
    BEGIN
        v_modulus := DBMS_CRYPTO.RANDOMBYTES(128);
        v_private_exp := DBMS_CRYPTO.RANDOMBYTES(128);
        
        -- Tạo Public Key
        v_public_key_raw := UTL_RAW.CONCAT(v_modulus, v_exponent);
        v_public_key_hex := RAWTOHEX(v_public_key_raw);
        
        -- Chuyển sang CLOB an toàn
        DBMS_LOB.CREATETEMPORARY(p_out_public_key, TRUE);
        DBMS_LOB.WRITEAPPEND(p_out_public_key, LENGTH(v_public_key_hex), v_public_key_hex);
        
        -- Tạo Private Key và mã hóa
        v_private_key_raw := UTL_RAW.CONCAT(v_modulus, v_private_exp);
        v_private_key_encrypted := DBMS_CRYPTO.ENCRYPT(
            src => v_private_key_raw,
            typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
            key => G_MASTER_KEY
        );
        v_private_key_hex := RAWTOHEX(v_private_key_encrypted);
        
        -- Chuyển sang CLOB an toàn
        DBMS_LOB.CREATETEMPORARY(p_out_private_key, TRUE);
        DBMS_LOB.WRITEAPPEND(p_out_private_key, LENGTH(v_private_key_hex), v_private_key_hex);
        
        -- Lưu vào database
        UPDATE NGUOI_DUNG 
        SET PUBLIC_KEY = p_out_public_key,
            PRIVATE_KEY_ENC = p_out_private_key
        WHERE MA_NGUOI_DUNG = p_ma_nguoi_dung;
        
        COMMIT;
        
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Lỗi tạo khóa cho user ' || p_ma_nguoi_dung || ': ' || SQLERRM);
            ROLLBACK;
            RAISE;
    END GEN_RSA_KEYPAIR;
    
    -- Mã hóa bằng RSA Public Key
    FUNCTION ENCRYPT_WITH_PUBLIC_KEY(
        p_public_key IN CLOB,
        p_data IN VARCHAR2
    ) RETURN RAW IS
        v_public_key_hex VARCHAR2(1000);
        v_public_key_raw RAW(500);
        v_data_raw RAW(2000);
        v_key_hash RAW(32);
    BEGIN
        IF p_public_key IS NULL OR p_data IS NULL THEN
            RETURN NULL;
        END IF;
        
        -- Chuyển CLOB → VARCHAR2 → RAW an toàn
        v_public_key_hex := DBMS_LOB.SUBSTR(p_public_key, 1000, 1);
        v_public_key_raw := HEXTORAW(v_public_key_hex);
        v_data_raw := UTL_I18N.STRING_TO_RAW(p_data, 'AL32UTF8');
        
        -- Hash public key để làm encryption key
        v_key_hash := DBMS_CRYPTO.HASH(v_public_key_raw, DBMS_CRYPTO.HASH_SH256);
        
        -- Mã hóa dữ liệu
        RETURN DBMS_CRYPTO.ENCRYPT(
            src => v_data_raw,
            typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
            key => v_key_hash
        );
        
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Lỗi mã hóa RSA: ' || SQLERRM);
            RETURN NULL;
    END ENCRYPT_WITH_PUBLIC_KEY;
    
    -- Giải mã bằng RSA Private Key
    FUNCTION DECRYPT_WITH_PRIVATE_KEY(
        p_private_key_enc IN CLOB,
        p_encrypted_data IN RAW
    ) RETURN VARCHAR2 IS
        v_private_key_hex VARCHAR2(4000);
        v_private_key_enc_raw RAW(2000);
        v_private_key_raw RAW(500);
        v_key_hash RAW(32);
        v_decrypted_data RAW(2000);
    BEGIN
        IF p_private_key_enc IS NULL OR p_encrypted_data IS NULL THEN
            RETURN NULL;
        END IF;
        
        v_private_key_hex := DBMS_LOB.SUBSTR(p_private_key_enc, 4000, 1);
        v_private_key_enc_raw := HEXTORAW(v_private_key_hex);
        
        v_private_key_raw := DBMS_CRYPTO.DECRYPT(
            src => v_private_key_enc_raw,
            typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
            key => G_MASTER_KEY
        );
        
        -- Hash private key để làm decryption key
        v_key_hash := DBMS_CRYPTO.HASH(v_private_key_raw, DBMS_CRYPTO.HASH_SH256);
        v_decrypted_data := DBMS_CRYPTO.DECRYPT(
            src => p_encrypted_data,
            typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
            key => v_key_hash
        );
        
        RETURN UTL_I18N.RAW_TO_CHAR(v_decrypted_data, 'AL32UTF8');
        
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Lỗi giải mã RSA: ' || SQLERRM);
            RETURN NULL;
    END DECRYPT_WITH_PRIVATE_KEY;
    
    -- MÃ HÓA LAI: AES + RSA
    FUNCTION HYBRID_ENCRYPT(
        p_public_key IN CLOB,
        p_data IN VARCHAR2,
        p_out_encrypted_aes_key OUT RAW
    ) RETURN RAW IS
        v_aes_key RAW(32);
        v_encrypted_data RAW(32767);
    BEGIN
        IF p_public_key IS NULL OR p_data IS NULL THEN
            RETURN NULL;
        END IF;
        
        v_aes_key := DBMS_CRYPTO.RANDOMBYTES(32);
        
        v_encrypted_data := DBMS_CRYPTO.ENCRYPT(
            src => UTL_I18N.STRING_TO_RAW(p_data, 'AL32UTF8'),
            typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
            key => v_aes_key
        );
        p_out_encrypted_aes_key := ENCRYPT_WITH_PUBLIC_KEY(
            p_public_key, 
            RAWTOHEX(v_aes_key)
        );
        
        RETURN v_encrypted_data;
        
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Lỗi mã hóa lai: ' || SQLERRM);
            RETURN NULL;
    END HYBRID_ENCRYPT;
    
    -- GIẢI MÃ LAI
    FUNCTION HYBRID_DECRYPT(
        p_private_key_enc IN CLOB,
        p_encrypted_data IN RAW,
        p_encrypted_aes_key IN RAW
    ) RETURN VARCHAR2 IS
        v_aes_key_hex VARCHAR2(100);
        v_aes_key RAW(32);
        v_decrypted_data RAW(32767);
    BEGIN
        IF p_private_key_enc IS NULL OR p_encrypted_data IS NULL OR p_encrypted_aes_key IS NULL THEN
            RETURN NULL;
        END IF;
        v_aes_key_hex := DECRYPT_WITH_PRIVATE_KEY(
            p_private_key_enc, 
            p_encrypted_aes_key
        );
        
        IF v_aes_key_hex IS NULL THEN
            RETURN NULL;
        END IF;
        
        v_aes_key := HEXTORAW(v_aes_key_hex);
        v_decrypted_data := DBMS_CRYPTO.DECRYPT(
            src => p_encrypted_data,
            typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
            key => v_aes_key
        );
        
        RETURN UTL_I18N.RAW_TO_CHAR(v_decrypted_data, 'AL32UTF8');
        
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Lỗi giải mã lai: ' || SQLERRM);
            RETURN NULL;
    END HYBRID_DECRYPT;
    
END PKG_MAHOA_LAI;
/

UPDATE NGUOI_DUNG SET PUBLIC_KEY = NULL, PRIVATE_KEY_ENC = NULL;
COMMIT;

SET SERVEROUTPUT ON;
BEGIN
    PROC_GEN_RSA_ALL_USERS();
    DBMS_OUTPUT.PUT_LINE('HOÀN THÀNH TẠO KHÓA RSA CHO TẤT CẢ USER');
END;
/
-- 4. PROCEDURE TẠO KHÓA RSA CHO TẤT CẢ USER
CREATE OR REPLACE PROCEDURE PROC_GEN_RSA_ALL_USERS IS
    v_pub CLOB;
    v_priv CLOB;
BEGIN
    FOR r IN (SELECT MA_NGUOI_DUNG FROM NGUOI_DUNG WHERE PUBLIC_KEY IS NULL) LOOP
        PKG_MAHOA_LAI.GEN_RSA_KEYPAIR(r.MA_NGUOI_DUNG, v_pub, v_priv);
        DBMS_OUTPUT.PUT_LINE('Generated RSA keys for user: ' || r.MA_NGUOI_DUNG);
    END LOOP;
    COMMIT;
END;
/

-- 5. PROCEDURE ĐIỂM DANH VỚI MÃ HÓA LAI
CREATE OR REPLACE PROCEDURE PROC_DIEMDANH_HYBRID(
    p_ma_buoi_hoc IN NUMBER,
    p_ma_sinh_vien IN NUMBER,
    p_phuong_thuc IN VARCHAR2,
    p_thiet_bi IN VARCHAR2,
    p_vi_tri IN VARCHAR2,
    p_trang_thai IN NVARCHAR2
) IS
    v_public_key CLOB;
    v_thiet_bi_enc RAW(32767);
    v_vi_tri_enc RAW(32767);
    v_aes_key_enc RAW(2000);
BEGIN
    -- Lấy Public Key của sinh viên
    SELECT PUBLIC_KEY INTO v_public_key 
    FROM NGUOI_DUNG 
    WHERE MA_NGUOI_DUNG = p_ma_sinh_vien;
    
    IF v_public_key IS NULL THEN
        RAISE_APPLICATION_ERROR(-20010, 'User chưa có RSA keypair!');
    END IF;
    
    -- Mã hóa THIET_BI bằng Hybrid Encryption
    v_thiet_bi_enc := PKG_MAHOA_LAI.HYBRID_ENCRYPT(
        v_public_key, 
        p_thiet_bi, 
        v_aes_key_enc
    );
    
    -- Mã hóa VI_TRI bằng Hybrid Encryption (tạo AES key mới)
    v_vi_tri_enc := PKG_MAHOA_LAI.HYBRID_ENCRYPT(
        v_public_key, 
        p_vi_tri, 
        v_aes_key_enc 
    );
    
    -- Lưu vào database
    INSERT INTO LICHSU_DIEMDANH (
        MA_BUOI_HOC, 
        MA_SINH_VIEN, 
        PHUONG_THUC, 
        TRANG_THAI,
        THIET_BI_ENC,
        VI_TRI_ENC,
        ENCRYPTED_AES_KEY
    ) VALUES (
        p_ma_buoi_hoc, 
        p_ma_sinh_vien, 
        p_phuong_thuc, 
        p_trang_thai,
        v_thiet_bi_enc,
        v_vi_tri_enc,
        v_aes_key_enc
    );
    COMMIT;
END;
/

-- 6. FUNCTION ĐỌC DỮ LIỆU ĐÃ MÃ HÓA LAI
CREATE OR REPLACE FUNCTION FUNC_GIAIMA_DIEMDANH(
    p_ma_log IN NUMBER,
    p_loai_du_lieu IN VARCHAR2 
) RETURN VARCHAR2 IS
    v_private_key_enc CLOB;
    v_encrypted_data RAW(32767);
    v_encrypted_aes_key RAW(2000);
    v_result VARCHAR2(4000);
BEGIN
    -- Lấy Private Key của sinh viên và dữ liệu mã hóa
    SELECT nd.PRIVATE_KEY_ENC, 
           CASE 
               WHEN p_loai_du_lieu = 'THIET_BI' THEN ls.THIET_BI_ENC
               ELSE ls.VI_TRI_ENC
           END,
           ls.ENCRYPTED_AES_KEY
    INTO v_private_key_enc, v_encrypted_data, v_encrypted_aes_key
    FROM LICHSU_DIEMDANH ls
    JOIN NGUOI_DUNG nd ON ls.MA_SINH_VIEN = nd.MA_NGUOI_DUNG
    WHERE ls.MA_LOG = p_ma_log;
    
    -- Giải mã bằng Hybrid Decryption
    v_result := PKG_MAHOA_LAI.HYBRID_DECRYPT(
        v_private_key_enc,
        v_encrypted_data,
        v_encrypted_aes_key
    );
    
    RETURN v_result;
END;
/

-- 7. CHẠY TẠO KHÓA CHO TẤT CẢ USER
BEGIN
    PROC_GEN_RSA_ALL_USERS();
END;
/



-- VIEW KIỂM TRA KHÓA RSA
CREATE OR REPLACE VIEW V_RSA_KEYS_STATUS AS
SELECT 
    MA_NGUOI_DUNG,
    TEN_DANG_NHAP,
    HO_TEN,
    CASE 
        WHEN PUBLIC_KEY IS NOT NULL THEN 'Có'
        ELSE 'Chưa có'
    END AS TRANG_THAI_PUBLIC_KEY,
    CASE 
        WHEN PRIVATE_KEY_ENC IS NOT NULL THEN 'Có (Encrypted)'
        ELSE 'Chưa có'
    END AS TRANG_THAI_PRIVATE_KEY,
    SUBSTR(PUBLIC_KEY, 1, 50) || '...' AS PUBLIC_KEY_PREVIEW
FROM NGUOI_DUNG
ORDER BY MA_NGUOI_DUNG;

-- THỐNG KÊ MÃ HÓA LAI
SELECT 
    COUNT(*) AS TONG_USER,
    COUNT(PUBLIC_KEY) AS USER_CO_RSA,
    COUNT(*) - COUNT(PUBLIC_KEY) AS USER_CHUA_CO_RSA,
    ROUND(COUNT(PUBLIC_KEY) * 100.0 / COUNT(*), 2) || '%' AS TY_LE_CO_RSA
FROM NGUOI_DUNG;

COMMIT;

--Proc thêm người dùng 
CREATE OR REPLACE PROCEDURE PROC_THEM_NGUOI_DUNG (
    p_user IN VARCHAR2, p_pass IN VARCHAR2, p_name IN NVARCHAR2, p_email IN VARCHAR2, p_role IN NUMBER
) IS
    v_salt VARCHAR2(100); v_hash VARCHAR2(255);
BEGIN
    v_salt := FUNC_GEN_SALT();    
    v_hash := FUNC_HASH_PASS(p_pass, v_salt);
    INSERT INTO NGUOI_DUNG (TEN_DANG_NHAP, MAT_KHAU_HASH, SALT, HO_TEN, EMAIL, MA_VAI_TRO)
    VALUES (p_user, v_hash, v_salt, p_name, p_email, p_role);
    COMMIT;
END;
/

-- 3.4 Proc Thêm Audit Log 
CREATE OR REPLACE PROCEDURE PROC_THEM_AUDIT_LOG (
    p_ma_nguoi_dung IN NUMBER,
    p_hanh_dong IN NVARCHAR2,
    p_chi_tiet IN NVARCHAR2,
    p_ip_address IN VARCHAR2,
    p_user_agent IN VARCHAR2,
    p_trang_thai IN NVARCHAR2
)
IS
BEGIN
    INSERT INTO AUDIT_LOG (MA_NGUOI_DUNG, HANH_DONG, CHI_TIET, IP_ADDRESS, USER_AGENT, TRANG_THAI)
    VALUES (p_ma_nguoi_dung, p_hanh_dong, p_chi_tiet, p_ip_address, p_user_agent, p_trang_thai);
    COMMIT;
END;
/

-- Function Kiểm tra đăng nhập
CREATE OR REPLACE FUNCTION FUNC_KIEMTRA_DANGNHAP (
    p_username IN VARCHAR2, p_password IN VARCHAR2
) RETURN NUMBER IS
    v_uid NUMBER; v_hash VARCHAR2(255); v_salt VARCHAR2(100);
BEGIN
    SELECT MA_NGUOI_DUNG, MAT_KHAU_HASH, SALT INTO v_uid, v_hash, v_salt
    FROM NGUOI_DUNG WHERE TEN_DANG_NHAP = p_username;
    
    IF FUNC_HASH_PASS(p_password, v_salt) = v_hash THEN RETURN v_uid;
    ELSE RETURN 0; END IF;
EXCEPTION WHEN NO_DATA_FOUND THEN RETURN -1;
END;
/

--Điều khiển truy cập dựa trên vai trò RBAC
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE ROLE R_GIANGVIEN;
CREATE ROLE R_SINHVIEN;

-- Giảng viên được xem danh sách SV, xem lớp, nhưng không được xóa user hệ thống
GRANT CONNECT TO R_GIANGVIEN;
GRANT CREATE SESSION TO R_GIANGVIEN;
GRANT SELECT, INSERT, UPDATE ON ADMIN_HUIT.LICHSU_DIEMDANH TO R_GIANGVIEN;
GRANT SELECT ON ADMIN_HUIT.LOP_HOC_PHAN TO R_GIANGVIEN;
GRANT SELECT ON ADMIN_HUIT.LICH_HOC TO R_GIANGVIEN;
GRANT SELECT ON ADMIN_HUIT.NGUOI_DUNG TO R_GIANGVIEN;

-- Sinh viên chỉ được xem lịch học, điểm danh của chính mình
GRANT CONNECT TO R_SINHVIEN;
GRANT CREATE SESSION TO R_SINHVIEN;
GRANT SELECT, INSERT ON ADMIN_HUIT.LICHSU_DIEMDANH TO R_SINHVIEN;
GRANT SELECT ON ADMIN_HUIT.LICH_HOC TO R_SINHVIEN;
GRANT SELECT ON ADMIN_HUIT.LOP_HOC_PHAN TO R_SINHVIEN;

-- VPD - Phân quyền dữ liệu
CREATE OR REPLACE FUNCTION FUNC_VPD_POLICY (
    p_schema IN VARCHAR2, p_object IN VARCHAR2
) RETURN VARCHAR2 AS
    v_user VARCHAR2(100);
BEGIN
    v_user := SYS_CONTEXT('USERENV', 'SESSION_USER');
    IF v_user = 'ADMIN_HUIT' THEN RETURN NULL;
    ELSE 
        RETURN 'MA_SINH_VIEN = (SELECT MA_NGUOI_DUNG FROM NGUOI_DUNG WHERE UPPER(TEN_DANG_NHAP) = ''' || v_user || ''')';
    END IF;
END;
/

BEGIN
    DBMS_RLS.ADD_POLICY (
        object_schema => 'ADMIN_HUIT',
        object_name   => 'LICHSU_DIEMDANH',
        policy_name   => 'VPD_STUDENT_VIEW',
        function_schema => 'ADMIN_HUIT',
        policy_function => 'FUNC_VPD_POLICY',
        statement_types => 'SELECT'
    );
END;
/

GRANT SELECT ON SYS.DBA_AUDIT_TRAIL TO ADMIN_HUIT;
GRANT SELECT ON SYS.DBA_FGA_AUDIT_TRAIL TO ADMIN_HUIT;
GRANT SELECT ON SYS.DBA_COMMON_AUDIT_TRAIL TO ADMIN_HUIT;

--TRIGGER AUDIT
CREATE OR REPLACE TRIGGER TRG_AUDIT_DB
AFTER INSERT OR UPDATE OR DELETE ON LICHSU_DIEMDANH
FOR EACH ROW
DECLARE v_user VARCHAR2(50);
BEGIN
    SELECT USER INTO v_user FROM DUAL; 
    
    IF INSERTING THEN
        INSERT INTO LOG_DB_CHANGES (USER_DB, ACTION_TYPE, TABLE_NAME, NEW_DATA)
        VALUES (v_user, 'INSERT', 'LICHSU_DIEMDANH', 'SV:' || :NEW.MA_SINH_VIEN || ' - TT:' || :NEW.TRANG_THAI);
    ELSIF UPDATING THEN
        INSERT INTO LOG_DB_CHANGES (USER_DB, ACTION_TYPE, TABLE_NAME, OLD_DATA, NEW_DATA)
        VALUES (v_user, 'UPDATE', 'LICHSU_DIEMDANH', 
                'Old TT:' || :OLD.TRANG_THAI, 'New TT:' || :NEW.TRANG_THAI);
    ELSIF DELETING THEN
        INSERT INTO LOG_DB_CHANGES (USER_DB, ACTION_TYPE, TABLE_NAME, OLD_DATA)
        VALUES (v_user, 'DELETE', 'LICHSU_DIEMDANH', 'Del SV:' || :OLD.MA_SINH_VIEN);
    END IF;
END;
/

-- STANDARD AUDIT và FGA 
AUDIT ALL ON ADMIN_HUIT.NGUOI_DUNG BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON ADMIN_HUIT.LICHSU_DIEMDANH BY ACCESS;

BEGIN
    DBMS_FGA.ADD_POLICY(
        object_schema => 'ADMIN_HUIT', object_name => 'NGUOI_DUNG', policy_name => 'FGA_CHECK_SENSITIVE',
        audit_condition => NULL, audit_column => 'EMAIL, MAT_KHAU_HASH', statement_types => 'SELECT, UPDATE'
    );
END;
/

-- View Audit Log của ứng dụng (từ bảng AUDIT_LOG)
CREATE OR REPLACE VIEW V_APP_AUDIT_LOG AS
SELECT 
    a.THOI_GIAN,
    u.HO_TEN,
    u.TEN_DANG_NHAP,
    a.HANH_DONG,
    a.CHI_TIET,
    a.IP_ADDRESS,
    a.TRANG_THAI
FROM AUDIT_LOG a
LEFT JOIN NGUOI_DUNG u ON a.MA_NGUOI_DUNG = u.MA_NGUOI_DUNG
ORDER BY a.THOI_GIAN DESC;

-- View Database Changes (từ trigger)
CREATE OR REPLACE VIEW V_DB_AUDIT AS
SELECT 
    ID_LOG,
    USER_DB,
    ACTION_TIME,
    ACTION_TYPE,
    TABLE_NAME,
    OLD_DATA,
    NEW_DATA
FROM LOG_DB_CHANGES
ORDER BY ACTION_TIME DESC;

-- View tổng hợp hoạt động điểm danh
CREATE OR REPLACE VIEW V_DIEMDANH_ACTIVITY AS
SELECT 
    l.THOI_GIAN_DIEM_DANH,
    sv.HO_TEN as SINH_VIEN,
    sv.TEN_DANG_NHAP as MSSV,
    mh.TEN_MON,
    gv.HO_TEN as GIANG_VIEN,
    l.PHUONG_THUC,
    l.TRANG_THAI,
    lh.PHONG_HOC
FROM LICHSU_DIEMDANH l
JOIN NGUOI_DUNG sv ON l.MA_SINH_VIEN = sv.MA_NGUOI_DUNG
JOIN LICH_HOC lh ON l.MA_BUOI_HOC = lh.MA_BUOI_HOC
JOIN LOP_HOC_PHAN lhp ON lh.MA_LOP_HP = lhp.MA_LOP_HP
JOIN MON_HOC mh ON lhp.MA_MON = mh.MA_MON
JOIN NGUOI_DUNG gv ON lhp.MA_GIANG_VIEN = gv.MA_NGUOI_DUNG
ORDER BY l.THOI_GIAN_DIEM_DANH DESC;

-- View thống kê bảo mật
CREATE OR REPLACE VIEW V_SECURITY_STATS AS
SELECT 
    (SELECT COUNT(*) FROM AUDIT_LOG WHERE TRANG_THAI = N'Thành công') as LOGIN_SUCCESS,
    (SELECT COUNT(*) FROM AUDIT_LOG WHERE TRANG_THAI = N'Thất bại') as LOGIN_FAILED,
    (SELECT COUNT(*) FROM LOG_DB_CHANGES WHERE ACTION_TYPE = 'INSERT') as TOTAL_INSERTS,
    (SELECT COUNT(*) FROM LOG_DB_CHANGES WHERE ACTION_TYPE = 'UPDATE') as TOTAL_UPDATES,
    (SELECT COUNT(*) FROM LOG_DB_CHANGES WHERE ACTION_TYPE = 'DELETE') as TOTAL_DELETES,
    (SELECT COUNT(*) FROM LICHSU_DIEMDANH WHERE TRUNC(THOI_GIAN_DIEM_DANH) = TRUNC(SYSDATE)) as TODAY_ATTENDANCE
FROM DUAL;



